<a href="https://colab.research.google.com/github/KhushbooGupta2111/Data-Analysis-With-Automotive-Industry-Engage/blob/main/Data_Cleaning_Log.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Cleaning 

In this, we have cleaned data of cars_engage_2022.csv (The dataset provided by Microsoft for Engage challenge)

The dataset is huge and needed an ample amount of cleaning for further processes in data analysis, data visualisation and training the machine learning model

The process of data cleaning included: 

1. Handling Missing Data
2.

Importing Libraries

In [7]:
import pandas as pd
import numpy as np

Importing Dataset

In [8]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

Dataset is available in the github repository under the Automotive_Industry_Data directory

In [9]:
auto_data = pd.read_csv('gdrive/My Drive/cars_engage_2022.csv')

Data Loaded.

In [10]:
auto_data["Clock"].value_counts()

Digital            1058
Analog               41
Yes                  39
Digital, Analog       4
Name: Clock, dtype: int64

Cleaning the data

1. Removing the index column

In [11]:
auto_data = auto_data.drop(auto_data.columns[0] , axis = 1)
auto_data

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271,Honda,City,Vx Mt Diesel,"Rs. 13,02,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,Yes,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1272,Honda,City,Zx Mt Diesel,"Rs. 14,21,000",1498 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS IV,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1273,Honda,City,Zx Cvt Petrol,"Rs. 14,31,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,Yes,Yes,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1274,Honda,City,V Cvt Petrol,"Rs. 12,01,000",1497 cc,4.0,4.0,FWD (Front Wheel Drive),In-line,BS 6,...,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN
1275,Mitsubishi,Montero,3.2 At,"Rs. 68,62,560",3200 cc,4.0,4.0,AWD (All Wheel Drive),In-line,BS IV,...,Yes,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN

2. Checking for all null values in all the columns in the dataset

In [12]:
null_values_dictionary = auto_data.isnull().sum().to_dict()
counter = 0;

for key , val in null_values_dictionary.items():
  if(val != 0):
    counter += 1
    print(str(key) + " - " + str(val))
  
print("The number of columns which have null values is: " + str(counter));

Make - 75
Displacement - 12
Cylinders - 66
Valves_Per_Cylinder - 102
Drivetrain - 7
Cylinder_Configuration - 13
Emission_Norm - 11
Engine_Location - 43
Fuel_System - 8
Fuel_Tank_Capacity - 69
Height - 1
Width - 12
Body_Type - 6
Doors - 4
City_Mileage - 555
Highway_Mileage - 800
ARAI_Certified_Mileage - 114
ARAI_Certified_Mileage_for_CNG - 1249
Kerb_Weight - 365
Gears - 105
Ground_Clearance - 289
Front_Brakes - 25
Rear_Brakes - 25
Front_Suspension - 59
Rear_Suspension - 46
Front_Track - 667
Rear_Track - 676
Front_Tyre_&_Rim - 49
Rear_Tyre_&_Rim - 48
Power_Steering - 57
Power_Windows - 97
Power_Seats - 893
Keyless_Entry - 274
Torque - 2
Odometer - 43
Speedometer - 45
Tachometer - 13
Tripmeter - 60
Seating_Capacity - 6
Seats_Material - 12
Type - 1
Wheelbase - 20
Wheels_Size - 56
Start_/_Stop_Button - 678
12v_Power_Outlet - 154
Audiosystem - 44
Aux-in_Compatibility - 284
Average_Fuel_Consumption - 345
Basic_Warranty - 440
Bluetooth - 292
Boot-lid_Opener - 14
Boot_Space - 249
CD_/_MP3_/_DVD_Player - 309
Central_Locking - 149
Child_Safety_Locks - 75
Clock - 134
Cup_Holders - 41
Distance_to_Empty - 243
Door_Pockets - 117
Engine_Malfunction_Light - 117
Extended_Warranty - 661
FM_Radio - 249
Fuel-lid_Opener - 14
Fuel_Gauge - 39
Handbrake - 57
Instrument_Console - 14
Low_Fuel_Warning - 36
Minimum_Turning_Radius - 381
Multifunction_Display - 89
Sun_Visor - 62
Third_Row_AC_Vents - 366
Ventilation_System - 35
Auto-Dimming_Rear-View_Mirror - 620
Hill_Assist - 796
Gear_Indicator - 499
3_Point_Seat-Belt_in_Middle_Rear_Seat - 1225
Ambient_Lightning - 1220
Cargo/Boot_Lights - 1155
Drive_Modes - 1081
Engine_Immobilizer - 60
High_Speed_Alert_System - 1068
Lane_Watch_Camera/_Side_Mirror_Camera - 1210
Passenger_Side_Seat-Belt_Reminder - 1105
Seat_Back_Pockets - 443
Voice_Recognition - 1144
Walk_Away_Auto_Car_Lock - 1173
ABS_(Anti-lock_Braking_System) - 132
Headlight_Reminder - 258
Adjustable_Headrests - 250
Gross_Vehicle_Weight - 595
Airbags - 132
Door_Ajar_Warning - 143
EBD_(Electronic_Brake-force_Distribution) - 201
Fasten_Seat_Belt_Warning - 190
Gear_Shift_Reminder - 543
Number_of_Airbags - 135
Compression_Ratio - 917
Adjustable_Steering_Column - 191
Other_Specs - 1266
Other_specs - 1213
Parking_Assistance - 290
Key_Off_Reminder - 340
USB_Compatibility - 267
Android_Auto - 1103
Apple_CarPlay - 1103
Cigarette_Lighter - 682
Infotainment_Screen - 462
Multifunction_Steering_Wheel - 351
Average_Speed - 512
EBA_(Electronic_Brake_Assist) - 690
Seat_Height_Adjustment - 326
Navigation_System - 593
Second_Row_AC_Vents - 602
Tyre_Pressure_Monitoring_System - 936
Rear_Center_Armrest - 559
iPod_Compatibility - 663
ESP_(Electronic_Stability_Program) - 779
Cooled_Glove_Box - 645
Recommended_Tyre_Pressure - 1266
Heated_Seats - 1010
Turbocharger - 618
ISOFIX_(Child-Seat_Mount) - 666
Rain_Sensing_Wipers - 798
Paddle_Shifters - 972
Leather_Wrapped_Steering - 689
Automatic_Headlamps - 774
Engine_Type - 1242
ASR_/_Traction_Control - 834
Cruise_Control - 727
USB_Ports - 1247
Heads-Up_Display - 1225
Welcome_Lights - 1207
Battery - 1263
Electric_Range - 1259
The number of columns which have null values is: 134

In [13]:
auto_data.shape

(1276, 140)

3. Make

In [14]:
company_names_list = auto_data.Make.unique().tolist()
print(type(company_names_list))
print(len(company_names_list))

for company in company_names_list:
  print(company)

<class 'list'>
40
Tata
Datsun
Renault
Maruti Suzuki
Hyundai
Premier
Toyota
Nissan
Volkswagen
Ford
Mahindra
Fiat
Honda
Jeep
Isuzu
Skoda
Audi
nan
Dc
Mini
Volvo
Jaguar
Bmw
Land Rover
Porsche
Lexus
Maserati
Lamborghini
Bentley
Ferrari
Aston Martin
Bugatti
Bajaj
Icml
Force
Mg
Kia
Land Rover Rover
Mitsubishi
Maruti Suzuki R

In [15]:
auto_data_Make = auto_data.Make.replace("Maruti Suzuki R" , "Maruti Suzuki") 
auto_data.head()

,Make,Model,Variant,Ex-Showroom_Price,Displacement,Cylinders,Valves_Per_Cylinder,Drivetrain,Cylinder_Configuration,Emission_Norm,...,Leather_Wrapped_Steering,Automatic_Headlamps,Engine_Type,ASR_/_Traction_Control,Cruise_Control,USB_Ports,Heads-Up_Display,Welcome_Lights,Battery,Electric_Range
0,Tata,Nano Genx,Xt,"Rs. 2,92,667",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tata,Nano Genx,Xe,"Rs. 2,36,447",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tata,Nano Genx,Emax Xm,"Rs. 2,96,661",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tata,Nano Genx,Xta,"Rs. 3,34,768",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tata,Nano Genx,Xm,"Rs. 2,72,223",624 cc,2.0,2.0,RWD (Rear Wheel Drive),In-line,BS IV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
for company in company_names_list:
   print(company)

Tata
Datsun
Renault
Maruti Suzuki
Hyundai
Premier
Toyota
Nissan
Volkswagen
Ford
Mahindra
Fiat
Honda
Jeep
Isuzu
Skoda
Audi
nan
Dc
Mini
Volvo
Jaguar
Bmw
Land Rover
Porsche
Lexus
Maserati
Lamborghini
Bentley
Ferrari
Aston Martin
Bugatti
Bajaj
Icml
Force
Mg
Kia
Land Rover Rover
Mitsubishi
Maruti Suzuki R

In [17]:
company_names = auto_data.Make
print(company_names)
print(type(company_names))

0             Tata
1             Tata
2             Tata
3             Tata
4             Tata
           ...
1271         Honda
1272         Honda
1273         Honda
1274         Honda
1275    Mitsubishi
Name: Make, Length: 1276, dtype: object
<class 'pandas.core.series.Series'>

In [18]:
np.where(company_names.isnull())[0]

array([ 252,  253,  254,  255,  256,  257,  258,  303,  307,  308,  309,
        310,  311,  322,  323,  324,  328,  329,  334,  335,  340,  349,
        350,  351,  353,  354,  793,  794,  795,  796,  797,  798,  799,
        800,  806,  809,  810,  811,  821,  859,  860,  861,  862,  879,
        880,  883,  884,  885,  886,  887,  888,  889,  890,  891, 1025,
       1026, 1033, 1034, 1035, 1036, 1037, 1038, 1047, 1048, 1049, 1146,
       1147, 1148, 1149, 1150, 1151, 1219, 1220, 1251, 1252])

In [19]:
company_names.isna().sum()

75

In [20]:
for name in company_names:
  print(name)

Tata
Tata
Tata
Tata
Tata
Tata
Datsun
Datsun
Datsun
Datsun
Datsun
Datsun
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Datsun
Datsun
Datsun
Datsun
Datsun
Datsun
Datsun
Datsun
Datsun
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Renault
Renault
Renault
Renault
Premier
Premier
Premier
Premier
Premier
Premier
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Nissan
Nissan
Nissan
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Mahindra
Mahindra
Mahindra
Fiat
Fiat
Fiat
Fiat
Toyota
Toyota
Toyota
Toyota
Toyota
Fiat
Fiat
Fiat
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Jeep
Jeep
Isuzu
Isuzu
Mahindra
Mahindra
Volkswagen
Volkswagen
Honda
Honda
Honda
Skoda
Skoda
Audi
Audi
Audi
Audi
nan
nan
nan
nan
nan
nan
nan
Skoda
Skoda
Skoda
Dc
Audi
Audi
Audi
Audi
Mini
Mini
Volvo
Volvo
Volvo
Mini
Audi
Audi
Mini
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Audi
Audi
Audi
Bmw
Bmw
Bmw
Land Rover
Land Rover
Volvo
Audi
Bmw
Bmw
Bmw
Ford
Jeep
Jeep
Jeep
Jeep
nan
Bmw
Porsche
Porsche
nan
nan
nan
nan
nan
Toyota
Lexus
Audi
Bmw
Bmw
Bmw
Bmw
Bmw
Bmw
Audi
nan
nan
nan
Maserati
Maserati
Maserati
nan
nan
Audi
Maserati
Maserati
Lexus
nan
nan
Porsche
Porsche
Porsche
Lexus
nan
Audi
Lamborghini
Bentley
Ferrari
Bentley
Bentley
Aston Martin
Ferrari
nan
nan
nan
Bentley
nan
nan
Bugatti
Bugatti
Bajaj
Bajaj
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Icml
Icml
Icml
Icml
Icml
Icml
Icml
Icml
Icml
Icml
Icml
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Fiat
Fiat
Fiat
Fiat
Fiat
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Ford
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Renault
Renault
Renault
Renault
Renault
Renault
Renault
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Volkswagen
Mahindra
Mahindra
Tata
Tata
Tata
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Mahindra
Mahindra
Mahindra
Force
Force
Force
Force
Force
Force
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Fiat
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Skoda
Skoda
Skoda
Skoda
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Tata
Tata
Tata
Tata
Tata
Tata
Tata
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Jeep
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Honda
Honda
Honda
Honda
Honda
Mg
Mg
Kia
Kia
Kia
Kia
Kia
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Volvo
Volvo
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Ford
Ford
Ford
Mini
Mini
Skoda
Bmw
Bmw
Bmw
Bmw
Bmw
Volvo
Volvo
Bmw
Bmw
Bmw
Volvo
Audi
Audi
Audi
Audi
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
nan
nan
nan
nan
nan
nan
nan
nan
Volvo
Bmw
Bmw
Bmw
Jeep
nan
Bmw
Bmw
nan
nan
nan
Audi
Audi
Audi
Audi
Audi
Audi
Land Rover Rover
Land Rover Rover
Land Rover Rover
nan
Volvo
Volvo
Volvo
Volvo
Volvo
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Jaguar
Jaguar
Jaguar
Porsche
Porsche
Porsche
Maserati
Maserati
Maserati
Toyota
Audi
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Land Rover Rover
Maserati
nan
nan
nan
nan
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Lamborghini
Ferrari
Ferrari
Ferrari
Ferrari
Lamborghini
Lamborghini
Lamborghini
nan
nan
Maruti Suzuki
Maruti Suzuki
nan
nan
nan
nan
nan
nan
nan
nan
nan
Fiat
Fiat
Ford
Ford
Ford
Ford
Ford
Ford
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Fiat
Fiat
Fiat
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Renault
Renault
Renault
Renault
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Kia
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Tata
Tata
Tata
Tata
Mg
Mg
Mg
Mg
Mg
Mg
Mg
Mg
Mg
Mg
Mg
Tata
Tata
Tata
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Volkswagen
Volkswagen
Volkswagen
Volkswagen
nan
nan
Volvo
Volvo
Mini
Mini
Mini
Mini
nan
nan
nan
nan
nan
nan
Toyota
Lexus
Lexus
Lexus
Jaguar
Jaguar
Volvo
Audi
nan
nan
nan
Bmw
Bmw
Bmw
Porsche
Porsche
Nissan
Aston Martin
Aston Martin
Ferrari
Maruti Suzuki
Maruti Suzuki
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Nissan
Nissan
Nissan
Nissan
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Maruti Suzuki
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Fiat
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Hyundai
Tata
Tata
Tata
Tata
Tata
Tata
Isuzu
Isuzu
Isuzu
Mitsubishi
nan
nan
nan
nan
nan
nan
Honda
Bmw
Bmw
Bmw
Bmw
Bmw
Bmw
Bmw
Porsche
Porsche
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Jaguar
Bmw
Lexus
Ferrari
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Maruti Suzuki R
Tata
Tata
Tata
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Mahindra
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Nissan
Tata
Hyundai
Toyota
Audi
Land Rover
Land Rover
Land Rover
Land Rover
Land Rover
Land Rover
Land Rover
Land Rover
Lexus
Lexus
Lexus
nan
nan
Fiat
Fiat
Fiat
Fiat
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Toyota
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
Skoda
nan
nan
Porsche
Porsche
Mahindra
Mahindra
Mahindra
Mitsubishi
Mitsubishi
Mitsubishi
Mitsubishi
Mitsubishi
Bentley
Bentley
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Honda
Mitsubishi

Model -- No null values present in this
Variant -- No null values present in this

In [21]:
auto_data.isnull().sum().to_dict()

{'12v_Power_Outlet': 154,
 '3_Point_Seat-Belt_in_Middle_Rear_Seat': 1225,
 'ABS_(Anti-lock_Braking_System)': 132,
 'ARAI_Certified_Mileage': 114,
 'ARAI_Certified_Mileage_for_CNG': 1249,
 'ASR_/_Traction_Control': 834,
 'Adjustable_Headrests': 250,
 'Adjustable_Steering_Column': 191,
 'Airbags': 132,
 'Ambient_Lightning': 1220,
 'Android_Auto': 1103,
 'Apple_CarPlay': 1103,
 'Audiosystem': 44,
 'Auto-Dimming_Rear-View_Mirror': 620,
 'Automatic_Headlamps': 774,
 'Aux-in_Compatibility': 284,
 'Average_Fuel_Consumption': 345,
 'Average_Speed': 512,
 'Basic_Warranty': 440,
 'Battery': 1263,
 'Bluetooth': 292,
 'Body_Type': 6,
 'Boot-lid_Opener': 14,
 'Boot_Space': 249,
 'CD_/_MP3_/_DVD_Player': 309,
 'Cargo/Boot_Lights': 1155,
 'Central_Locking': 149,
 'Child_Safety_Locks': 75,
 'Cigarette_Lighter': 682,
 'City_Mileage': 555,
 'Clock': 134,
 'Compression_Ratio': 917,
 'Cooled_Glove_Box': 645,
 'Cruise_Control': 727,
 'Cup_Holders': 41,
 'Cylinder_Configuration': 13,
 'Cylinders': 66,
 'Displacement': 12,
 'Distance_to_Empty': 243,
 'Door_Ajar_Warning': 143,
 'Door_Pockets': 117,
 'Doors': 4,
 'Drive_Modes': 1081,
 'Drivetrain': 7,
 'EBA_(Electronic_Brake_Assist)': 690,
 'EBD_(Electronic_Brake-force_Distribution)': 201,
 'ESP_(Electronic_Stability_Program)': 779,
 'Electric_Range': 1259,
 'Emission_Norm': 11,
 'Engine_Immobilizer': 60,
 'Engine_Location': 43,
 'Engine_Malfunction_Light': 117,
 'Engine_Type': 1242,
 'Ex-Showroom_Price': 0,
 'Extended_Warranty': 661,
 'FM_Radio': 249,
 'Fasten_Seat_Belt_Warning': 190,
 'Front_Brakes': 25,
 'Front_Suspension': 59,
 'Front_Track': 667,
 'Front_Tyre_&_Rim': 49,
 'Fuel-lid_Opener': 14,
 'Fuel_Gauge': 39,
 'Fuel_System': 8,
 'Fuel_Tank_Capacity': 69,
 'Fuel_Type': 0,
 'Gear_Indicator': 499,
 'Gear_Shift_Reminder': 543,
 'Gears': 105,
 'Gross_Vehicle_Weight': 595,
 'Ground_Clearance': 289,
 'Handbrake': 57,
 'Headlight_Reminder': 258,
 'Heads-Up_Display': 1225,
 'Heated_Seats': 1010,
 'Height': 1,
 'High_Speed_Alert_System': 1068,
 'Highway_Mileage': 800,
 'Hill_Assist': 796,
 'ISOFIX_(Child-Seat_Mount)': 666,
 'Infotainment_Screen': 462,
 'Instrument_Console': 14,
 'Kerb_Weight': 365,
 'Key_Off_Reminder': 340,
 'Keyless_Entry': 274,
 'Lane_Watch_Camera/_Side_Mirror_Camera': 1210,
 'Leather_Wrapped_Steering': 689,
 'Length': 0,
 'Low_Fuel_Warning': 36,
 'Make': 75,
 'Minimum_Turning_Radius': 381,
 'Model': 0,
 'Multifunction_Display': 89,
 'Multifunction_Steering_Wheel': 351,
 'Navigation_System': 593,
 'Number_of_Airbags': 135,
 'Odometer': 43,
 'Other_Specs': 1266,
 'Other_specs': 1213,
 'Paddle_Shifters': 972,
 'Parking_Assistance': 290,
 'Passenger_Side_Seat-Belt_Reminder': 1105,
 'Power': 0,
 'Power_Seats': 893,
 'Power_Steering': 57,
 'Power_Windows': 97,
 'Rain_Sensing_Wipers': 798,
 'Rear_Brakes': 25,
 'Rear_Center_Armrest': 559,
 'Rear_Suspension': 46,
 'Rear_Track': 676,
 'Rear_Tyre_&_Rim': 48,
 'Recommended_Tyre_Pressure': 1266,
 'Seat_Back_Pockets': 443,
 'Seat_Height_Adjustment': 326,
 'Seating_Capacity': 6,
 'Seats_Material': 12,
 'Second_Row_AC_Vents': 602,
 'Speedometer': 45,
 'Start_/_Stop_Button': 678,
 'Sun_Visor': 62,
 'Tachometer': 13,
 'Third_Row_AC_Vents': 366,
 'Torque': 2,
 'Tripmeter': 60,
 'Turbocharger': 618,
 'Type': 1,
 'Tyre_Pressure_Monitoring_System': 936,
 'USB_Compatibility': 267,
 'USB_Ports': 1247,
 'Valves_Per_Cylinder': 102,
 'Variant': 0,
 'Ventilation_System': 35,
 'Voice_Recognition': 1144,
 'Walk_Away_Auto_Car_Lock': 1173,
 'Welcome_Lights': 1207,
 'Wheelbase': 20,
 'Wheels_Size': 56,
 'Width': 12,
 'iPod_Compatibility': 663}

In [22]:
num_features=[col for col in auto_data.columns if auto_data[col].dtypes !='O']
cat_features=[col for col in auto_data.columns if col not in num_features]
print("categorical features:\n{}".format(cat_features),"\n")
print("numerical features:\n{}".format(num_features))

categorical features:
['Make', 'Model', 'Variant', 'Ex-Showroom_Price', 'Displacement', 'Drivetrain', 'Cylinder_Configuration', 'Emission_Norm', 'Engine_Location', 'Fuel_System', 'Fuel_Tank_Capacity', 'Fuel_Type', 'Height', 'Length', 'Width', 'Body_Type', 'City_Mileage', 'Highway_Mileage', 'ARAI_Certified_Mileage', 'ARAI_Certified_Mileage_for_CNG', 'Kerb_Weight', 'Gears', 'Ground_Clearance', 'Front_Brakes', 'Rear_Brakes', 'Front_Suspension', 'Rear_Suspension', 'Front_Track', 'Rear_Track', 'Front_Tyre_&_Rim', 'Rear_Tyre_&_Rim', 'Power_Steering', 'Power_Windows', 'Power_Seats', 'Keyless_Entry', 'Power', 'Torque', 'Odometer', 'Speedometer', 'Tachometer', 'Tripmeter', 'Seats_Material', 'Type', 'Wheelbase', 'Wheels_Size', 'Start_/_Stop_Button', '12v_Power_Outlet', 'Audiosystem', 'Aux-in_Compatibility', 'Average_Fuel_Consumption', 'Basic_Warranty', 'Bluetooth', 'Boot-lid_Opener', 'Boot_Space', 'CD_/_MP3_/_DVD_Player', 'Central_Locking', 'Child_Safety_Locks', 'Clock', 'Cup_Holders', 'Distance_to_Empty', 'Door_Pockets', 'Engine_Malfunction_Light', 'Extended_Warranty', 'FM_Radio', 'Fuel-lid_Opener', 'Fuel_Gauge', 'Handbrake', 'Instrument_Console', 'Low_Fuel_Warning', 'Minimum_Turning_Radius', 'Multifunction_Display', 'Sun_Visor', 'Third_Row_AC_Vents', 'Ventilation_System', 'Auto-Dimming_Rear-View_Mirror', 'Hill_Assist', 'Gear_Indicator', '3_Point_Seat-Belt_in_Middle_Rear_Seat', 'Ambient_Lightning', 'Cargo/Boot_Lights', 'Drive_Modes', 'Engine_Immobilizer', 'High_Speed_Alert_System', 'Lane_Watch_Camera/_Side_Mirror_Camera', 'Passenger_Side_Seat-Belt_Reminder', 'Seat_Back_Pockets', 'Voice_Recognition', 'Walk_Away_Auto_Car_Lock', 'ABS_(Anti-lock_Braking_System)', 'Headlight_Reminder', 'Adjustable_Headrests', 'Gross_Vehicle_Weight', 'Airbags', 'Door_Ajar_Warning', 'EBD_(Electronic_Brake-force_Distribution)', 'Fasten_Seat_Belt_Warning', 'Gear_Shift_Reminder', 'Compression_Ratio', 'Adjustable_Steering_Column', 'Other_Specs', 'Other_specs', 'Parking_Assistance', 'Key_Off_Reminder', 'USB_Compatibility', 'Android_Auto', 'Apple_CarPlay', 'Cigarette_Lighter', 'Infotainment_Screen', 'Multifunction_Steering_Wheel', 'Average_Speed', 'EBA_(Electronic_Brake_Assist)', 'Seat_Height_Adjustment', 'Navigation_System', 'Second_Row_AC_Vents', 'Tyre_Pressure_Monitoring_System', 'Rear_Center_Armrest', 'iPod_Compatibility', 'ESP_(Electronic_Stability_Program)', 'Cooled_Glove_Box', 'Recommended_Tyre_Pressure', 'Heated_Seats', 'Turbocharger', 'ISOFIX_(Child-Seat_Mount)', 'Rain_Sensing_Wipers', 'Paddle_Shifters', 'Leather_Wrapped_Steering', 'Automatic_Headlamps', 'Engine_Type', 'ASR_/_Traction_Control', 'Cruise_Control', 'Heads-Up_Display', 'Welcome_Lights', 'Battery', 'Electric_Range']

numerical features:
['Cylinders', 'Valves_Per_Cylinder', 'Doors', 'Seating_Capacity', 'Number_of_Airbags', 'USB_Ports']

Function which removes all the values after the first spacebar in the column

Function Built for cleaning Delimiter 

(Note: This just removes the extra units. For converting the values from string to integer, run the string_to_numeric function, which is mentioned below)

In [23]:
auto_data.isnull().sum()

Make                   75
Model                   0
Variant                 0
Ex-Showroom_Price       0
Displacement           12
                     ...
USB_Ports            1247
Heads-Up_Display     1225
Welcome_Lights       1207
Battery              1263
Electric_Range       1259
Length: 140, dtype: int64

In [24]:
# This function is used to eliminate the delimiter values in the columns
def unit_delimiter(column_name , removing_substring):
  auto_data[column_name] = auto_data[column_name].apply(str).str.replace(' ' + removing_substring , '');

Function Built for converting values from string to integer 

(Note: Run this after you have executed the function unit_delimiter)

In [25]:
def string_to_numeric(column_name):
  auto_data[column_name] = auto_data[column_name].fillna(0)
  auto_data[column_name] = auto_data[column_name].replace("nan" , 0 , regex = True)
  auto_data[column_name] = pd.to_numeric(auto_data[column_name] )

A function which combines these 2 functions

In [26]:
def delimiter_and_numeric(column_name , removing_substring):
  unit_delimiter(column_name , removing_substring)
  string_to_numeric(column_name)

In [27]:
def all_before_space(column_name):
  auto_data[column_name] = auto_data[column_name].str.split(" " , n = 1 , expand = True)[0]

:::::Function which replaces any extra character from the column

In [28]:
def replace_extra_characters(column_name , character , replacement = ''):
  auto_data[column_name] = auto_data[column_name].str.replace(character , replacement)